
# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models


def update_alternate_exams(apps, schema_editor):

    alternate_exams = apps.get_model('students', 'AlternateExams')
    old_test_grade_level_six = "6th grade"
    new_test_grade_level_six = "6th Grade"

    alternate_exams.objects.filter(ela_test_grade_level=old_test_grade_level_six).update(
        ela_test_grade_level=new_test_grade_level_six
    )
    alternate_exams.objects.filter(math_test_grade_level=old_test_grade_level_six).update(
        math_test_grade_level=new_test_grade_level_six
    )


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0126_auto_20210318_1030'),
    ]
    operations = [
        migrations.AlterField(
            model_name='alternateexams',
            name='ela_test_grade_level',
            field=models.CharField(
                blank=True, 
                choices=[('3rd Grade', '3rd Grade (in previous school year)'), 
                         ('4th Grade', '4th Grade (in previous school year)'), 
                         ('5th Grade', '5th Grade (in previous school year)'), 
                         ('6th Grade', '6th Grade (in previous school year)'), 
                         ('7th Grade', '7th Grade (in previous school year)'), 
                         ('8th Grade', '8th Grade (in previous school year)')], 
                max_length=63, verbose_name='ELA Test Grade Level'),
        ),
        migrations.AlterField(
            model_name='alternateexams',
            name='math_test_grade_level',
            field=models.CharField(
                blank=True, 
                choices=[('3rd Grade', '3rd Grade (in previous school year)'), 
                         ('4th Grade', '4th Grade (in previous school year)'), 
                         ('5th Grade', '5th Grade (in previous school year)'), 
                         ('6th Grade', '6th Grade (in previous school year)'), 
                         ('7th Grade', '7th Grade (in previous school year)'), 
                         ('8th Grade', '8th Grade (in previous school year)')], 
                max_length=63, verbose_name='Math Test Grade Level'),
        ),
        migrations.RunPython(
            update_alternate_exams,
            reverse_code=migrations.RunPython.noop
        )
    ]
